services:
  nginx:
    build: api/docker/dev/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./api:/app
    depends_on:
      - php-fpm

  php-cli:
    build: api/docker/dev/php-cli
    restart: unless-stopped
    volumes:
      - ./api:/app
      - composer:/root/.composer/cache
    depends_on:
      - mysql
      - redis

  php-fpm:
    build: api/docker/dev/php-fpm
    restart: unless-stopped
    volumes:
      - ./api:/app
    depends_on:
      - mysql
      - redis

  mysql:
    build: api/docker/dev/mysql
    restart: unless-stopped
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis:6.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  composer:
  mysql:
  redis: